# Generated by Django 4.1.4 on 2025-05-27 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cubaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceluploadlog',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Excel Upload Log', 'verbose_name_plural': 'Excel Upload Logs'},
        ),
        migrations.AlterField(
            model_name='exceluploadlog',
            name='file_name',
            field=models.CharField(help_text='Original name of the uploaded file', max_length=255),
        ),
        migrations.AlterField(
            model_name='exceluploadlog',
            name='row_count',
            field=models.PositiveIntegerField(help_text='How many rows were processed'),
        ),
        migrations.AlterField(
            model_name='exceluploadlog',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded'),
        ),
        migrations.AlterField(
            model_name='exceluploadlog',
            name='user',
            field=models.ForeignKey(db_column='user_id', help_text='The user who performed the upload', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
