# Generated by Django 4.1.4 on 2025-05-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0002_alter_exceluploadlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelrecord',
            name='emertimi_i_artikullit',
            field=models.CharField(max_length=500, verbose_name='Emertimi I Artikullit'),
        ),
        migrations.AlterField(
            model_name='excelrecord',
            name='emri_i_aksionit',
            field=models.CharField(max_length=500, verbose_name='Emri I Aksionit'),
        ),
        migrations.AlterField(
            model_name='excelrecord',
            name='furnitori',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Furnitori'),
        ),
        migrations.AlterField(
            model_name='excelrecord',
            name='pako_ame',
            field=models.TextField(blank=True, help_text='Any length of text describing the package', null=True, verbose_name='Pako (Ame)'),
        ),
    ]
