# Generated by Django 4.1.4 on 2025-05-27 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cubaapp', '0003_alter_excelrecord_emertimi_i_artikullit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceluploadlog',
            name='user',
            field=models.ForeignKey(db_column='user_id', help_text='The user who performed the upload', on_delete=django.db.models.deletion.CASCADE, related_name='excel_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
