# Generated by Django 4.1.4 on 2025-05-28 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0005_excelrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelrecord',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='exceluploadlog',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
